# Generated by Django 2.0.2 on 2018-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fname', models.CharField(max_length=100)),
                ('student_lname', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=50)),
                ('student_username', models.CharField(max_length=100)),
                ('student_password', models.CharField(max_length=20)),
                ('student_date', models.DateField()),
            ],
        ),
    ]
